# Generated by Django 5.1 on 2024-11-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfaceregister', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acesso',
        ),
    ]
